### ISSUE TITLE
Refresh documentation

### ISSUE THREAD

**Issue by bluesabre** [Xubuntu/xubuntu-docs#2]
This is an ongoing project, with files collaborated on in [Google Docs](https://drive.google.com/drive/folders/10nsLPokttFjG9g4x4mLBYNkTyO0izy5H).

**Comment by skellat** [comment]
If we can make a Stable Release Update for 20.04.1 that would be a beautiful thing to do as well.

**Comment by bluesabre** [comment]
> If we can make a Stable Release Update for 20.04.1 that would be a beautiful thing to do as well.

20.04.1 will be released on July 23, so we should aim for getting that updated release out for early July. We'll have some nice translation updates by then as well.

**Comment by skellat** [comment]
See: https://discourse.ubuntu.com/t/20-04-1-lts-release-candidate-isos-ready-for-testing/17615

Although the .1 release for 20.04 appears targeted for August 6th it looks like we won't be ready on the documentation at this point.

**Comment by philipzae** [comment]
The revised documentation is intended for 20.10 and not 20.04.1, assuming we can finish the revised docs this month.

20.04.1 will have translation updates for the old documentation from transifex.

**Comment by skellat** [comment]
We're down to the last chapter and should be converting things back to DocBook at this point.

**Comment by philipzae** [comment]
Converting to docbook is in process, so we'll definitely have this ready for 21.10.
